apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: # these are replicaset labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector:
    # these are used to select the pod to create replicas
    matchLabels:
      tier: frontend
      app: nginx
  # this is pod definition
  template:
    metadata:
      # these labels belong to pods
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
      # This is called a placeholder
        image: nginx:{{ .Values.deployment.imageVersion }}
